### ISSUE TITLE
Process Scientific Target

### ISSUE THREAD

**Issue by sergiopasra** [guaix-ucm/megaradrp#17]
Related tasks are:
- [x] Process LCB IFU Fast Mapping #32
- [x] Process Fiber MOS #31 
- [x] Process LCB IFU #18
